services:
  - type: web
    name: ikigai-quiz
    env: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ikigai-quiz-db
          property: connectionString
      - key: ADMIN_API_KEY
        sync: false

databases:
  - name: ikigai-quiz-db
    databaseName: ikigai_quiz
    user: ikigai_quiz_user
    plan: free
